# Generated by Django 3.0.3 on 2020-02-14 00:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="invitation", name="a",),
        migrations.AddField(
            model_name="profileimage",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_images",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
