# Generated by Django 3.0.3 on 2020-02-14 01:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_auto_20200214_0025"),
    ]

    operations = [
        migrations.RemoveField(model_name="invitation", name="used",),
        migrations.AlterField(
            model_name="invitation",
            name="used_by",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="joined_invitation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
