# Generated by Django 3.0.3 on 2020-02-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_auto_20200214_1650"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="card_template_id",
            field=models.IntegerField(default=1),
        ),
    ]
